### ISSUE TITLE
break line

### ISSUE THREAD

**Issue by dax44** [stefano-meschiari/latex2exp#10]
How to do break in line? For example I want to get:
This is first line of plot title
and this is the next

**Comment by stefano-meschiari** [comment]
You can use `\n` to break the line. E.g. 
```r
TeX("This is first line of plot title\nand this is the next")
```

**Comment by dax44** [comment]
Yes but if I use LaTeX frase like 
`TeX("This is first line of plot title $a^3\\sin(x)$ \n and this is the next")`
it didn't work :(
