### ISSUE TITLE
output = "text" inconsistent with output = "character"

### ISSUE THREAD

**Issue by Aariq** [stefano-meschiari/latex2exp#12]
According to the help file, output = "text" returns a string, but it actually returns an expression the same as output = "expression".  It should be output = "character" in the help file or the function should be changed so output = "text" works.

**Comment by caijun** [comment]
I found the same problem in the help file. I documented in my issue https://github.com/stefano-meschiari/latex2exp/issues/13

**Comment by Aariq** [comment]
It appears that this has been fixed as of the most recent commit.  It now gives a helpful error message if you try to use output = "text" and the help file has been updated to use "character".

**Comment by Aariq** [comment]
Install the most recent development version with `devtools::install_github("stefano-meschiari/latex2exp")`
