### ISSUE TITLE
Entry point not found

### ISSUE THREAD

**Issue by luisvalenzuelar** [stefano-meschiari/latex2exp#14]
I installed the latest latex2exp manually from the binary available in CRAN, in a Windows computer without internet (I am working in a secure lab environment). I am using R 3.3.1, with RGui (crap, I know, but I am not an administrator and change requests are slow). When I load the package, I get a pop-up message saying:

>The procedure entry point DATAPTR could not be located in the dynamic link library R.dll.

After accepting the message, the R console says:

>Error in inDL(x, as.logical(local), as.logical(now), ... ) :
 unable to load shared object '//path/to/my/local/library/stringi/libs/x64/stringi.dll :
 LoadLibrary failure: The specified procedure could not be found.

Not sure what is the problem, as the file stringi.dll **is** in the aforementioned folder. The file is the original from the package .zip file.

I manually installed other packages and dependencies (like ggplot2) and they load fine, so it seems to be an issue of latex2exp. Hence my post here. Any idea?

**Comment by gregkvas** [comment]
I experienced that "Entry Point" error messages occure when using R and packages of different builts , e.g. using R 3.4 on packages of built 3.5 or the other way round...check if your R Version and packages are homogenous (use "installed.packages()") and try to re-install packages of current R Version which are not...this may solve the issue...

**Comment by stefano-meschiari** [comment]
Apologies for the long delay in answering this issue 😞 

I will close this issue since it's been open for so long, but if you still experience this issue in the newest released version (0.9.0), please file a new issue.
