### ISSUE TITLE
extra space between expressions does not work

### ISSUE THREAD

**Issue by nmolanog** [stefano-meschiari/latex2exp#16]
Extra space symbol "~" is not, working for example:
`TeX('$H_0:~E(Dif) = 0$')`

**Comment by GegznaV** [comment]
As a workaround, you may try either `\\,` or `\\;`, e.g., `TeX('$H_0:\\;\\,E(Dif) = 0$')` results in:
![image](https://user-images.githubusercontent.com/12725868/46789805-1647a900-cd46-11e8-90b7-97292f988423.png)


But it  **would be nice to have** both `~` and `\\ ` (space preceded with a slash) interpreted as a space in math mode of the equation too.
