### ISSUE TITLE
Add possibility to use literal underscore (_) and caret (^) symbols

### ISSUE THREAD

**Issue by GegznaV** [stefano-meschiari/latex2exp#17]
Add possibility to use literal underscore and caret symbols. Now I can't use them neither in text, nor in math modes.

 `TeX('H_0\\_1\\^2 $H_3\\_4\\^5$')`: 
![image](https://user-images.githubusercontent.com/12725868/46790817-6d4e7d80-cd48-11e8-99eb-6037002ce062.png)

**Comment by shgoke** [comment]
I'd appreciate it if you could add literal dollar sign ($).

**Comment by stefano-meschiari** [comment]
Sorry for the delay in answering this issue.

As of 0.9.0, this should work correctly:

```
plot(TeX(r'($a\^b\_c\$$)'))
```
![image](https://user-images.githubusercontent.com/2151723/150884369-61181557-c0e5-4951-9879-5b0ed0a2715d.png)
