### ISSUE TITLE
The symbol of absolute value in TeX()?

### ISSUE THREAD

**Issue by fountainer** [stefano-meschiari/latex2exp#18]
The code `TeX("$\\hat{|\\rho|}$")` gives the following error:
```
Original string:  $\hat{|\rho|}$ 
Parsed expression:  paste('','',hat(paste('|',rho|,,,)),'') 
Error in parse(text = str) : <text>:1:31: unexpected ','
1: paste('','',hat(paste('|',rho|,
```

**Comment by goepp** [comment]
I have the same problem and have found no work-around.

**Comment by DSLituiev** [comment]
any update on this?

**Comment by DSLituiev** [comment]
For me following worked: `TeX("$\\hat{ | \\rho |}$")` -- add spaces around the pipe

**Comment by stefano-meschiari** [comment]
Sorry for the delay in answering to this issue.

This should correctly work in 0.9.0 (`plot(TeX("$|\\hat{\\rho}|$"))`)
