### ISSUE TITLE
horizontal spacing didn't work (for me)

### ISSUE THREAD

**Issue by rcorty** [stefano-meschiari/latex2exp#19]
not sure if i was doing it right, but I couldn't get whitespace with 

$\;$ nor $\,$

Would be great to support, e.g. \hspace{2cm} as well

**Comment by rcorty** [comment]
The line from my ggplot was

        xlab(TeX(paste('lower $V_e \;$'strain')))

**Comment by billy34** [comment]
You have to escape twice `\\;` instead of `\;` as it's an R string
```
xlab(TeX(paste('lower $V_e \\;$'strain')))
```

**Comment by stefano-meschiari** [comment]
Sorry for the delay in answering this issue. As @billy34 mentioned, you need to escape the backslash (`\\;`) or use the new R raw string syntax, which would look like

```
TeX(r'(lower $V_e \;$'strain)')
```
