### ISSUE TITLE
Remove space after decimal point

### ISSUE THREAD

**Issue by dppalomar** [stefano-meschiari/latex2exp#20]
For some reason a blank space is automatically added after a decimal point and I don't understand why.
For example, see:
```{r}
TeX("3.3")
># expression(`3.3` = paste("3", ". 3"))
```
when it should produce
```{r}
># expression(`3.3` = paste("3", ".3"))
```
See it in a plot:
```{r}
plot(1:4, 1:4, main = TeX("3.3"))
```
Any way to fix this?
Thanks.

**Comment by wzel** [comment]
I second this. See PR #21.

**Comment by dppalomar** [comment]
Thanks @wzel !
