### ISSUE TITLE
Using "\left(" with "\right." - bgroup is not correctly constructed

### ISSUE THREAD

**Issue by kathsel** [stefano-meschiari/latex2exp#24]
In LaTeX one can construct a large open parenthesis with `\left(\frac{M}{L}\right.`. Using this with `TeX` is possible and gives: 
```r
TeX("$\\left(\\frac{M}{L}\\right.$")
#> expression(`$\left(\frac{M}{L}\right.$` = 
#>            paste("", "", bgroup("(", paste("", frac(paste("M"), paste("", "L")), ""))))
```
It is not possible to use this as the `bgroup` is missing the "closing" dot. The correct code would be: 
`expression(bgroup("(", frac("M", "L"), "."))` (I removed unneccessary `paste` and empty strings, for emphasis on the `"."`). 

```r
plot.new()
plot.window(c(0,3), c(0,1))
text(0, 0.5, latex2exp::TeX("$\\left(\\frac{M}{L}\\right)$")) # works
text(1, 0.5, latex2exp::TeX("$\\left(\\frac{M}{L}\\right.$")) 
```
> Error in bgroup("(", paste("", frac(paste("M"), paste("", "L")), "")) : 
  invalid group specification
```r
text(2, 0.5, expression(bgroup("(", frac("M", "L"), "."))) # works
```
![grafik](https://user-images.githubusercontent.com/31727892/72245076-f9a4bb80-35ef-11ea-8d92-3cf3342cd016.png)

**Comment by stefano-meschiari** [comment]
This bug is now fixed in the latest release (v0.9.0).
