### ISSUE TITLE
closing braces

### ISSUE THREAD

**Issue by piantado** [stefano-meschiari/latex2exp#26]
Closing braces don't seem to show up for me (R 3.6.1 on ubuntu):

library(latex2exp)
plot(1:10, main=TeX("$\\{ x \\}$") )

**Comment by NMarkgraf** [comment]
Same problem here. It seems that the last "}" will be ignored, except you use "\\left{" and "\\right}". Then it works perfectly.

**Comment by NMarkgraf** [comment]
Wow! This https://github.com/stefano-meschiari/latex2exp/commit/a273edc15286bfe5868a3d2067375cf9d42c44d3 should fix the problem. It was written in 2017, we have 2020 ... I guess this project is dead.

**Comment by stefano-meschiari** [comment]
Apologies for the delay in addressing this. The newest release (0.9.0) fixes this bug.
