### ISSUE TITLE
TeX() output arg choice should be "character" not "text"

### ISSUE THREAD

**Issue by dholstius** [stefano-meschiari/latex2exp#27]
Thank you for a wonderful package!! Just a minor bug. 

The function signature for `TeX()` is:

```
function (string, output = c("expression", "text", "ast")) 
```

... but the signature for `.parseTeX()` is:

```
function (string, output = c("expression", "character", "ast")) 
```

Passing `output = "text"` to `TeX()` therefore fails to produce the desired result (but passing `output = "character"` does).

**Comment by stefano-meschiari** [comment]
Fixed in 0.9.0.
