### ISSUE TITLE
Possibility to include \vdots and \ddots

### ISSUE THREAD

**Issue by luifrancgom** [stefano-meschiari/latex2exp#32]
I was annotating a plot that was build using `ggplot2`. I tried to use `TeX($\\vdots$)` and `TeX($\\ddots$)` but these options are not supported by `latex2exp`.

Can you include them in `latex2exp`?

Best wishes and thank you for building the package `latex2exp`

**Comment by stefano-meschiari** [comment]
Unfortunately, as far as I know, this is not supported by R. latex2exp translates LaTeX to plotmath expressions (`?plotmath`), so it can only support commands and symbols that have a direct equivalent in plotmath.
