### ISSUE TITLE
Add ceil and floor symbols

### ISSUE THREAD

**Issue by AntoineSoetewey** [stefano-meschiari/latex2exp#33]
Hello,

Unless I'm mistaken, \lceil, \rceil, \lfloor and \rfloor symbols are not supported (see section "Supported LaTeX" in this [vignette](https://cran.r-project.org/web/packages/latex2exp/vignettes/using-latex2exp.html)).

I would like to use the \rceil symbol in the axis label of my plot, would you mind adding these symbols?

Thanks in advance for your help and for building this package.

Regards,
Antoine

**Comment by stefano-meschiari** [comment]
Hi Antoine,

Sorry for taking so long to address this FR. Would you be able to try this pre-release version (0.9.0) and test `\lceil / \lfloor`?

https://github.com/stefano-meschiari/latex2exp/tree/0.9.0

**Comment by stefano-meschiari** [comment]
As an example,
```
TeX(r"($\lceil a+b \rceil$)")
```
currently renders as
![image](https://user-images.githubusercontent.com/2151723/150444057-0babecb8-7bde-4284-ae5d-aa04ad50fb2c.png)
in the new version.

**Comment by AntoineSoetewey** [comment]
Thanks for your reply.

I have tried but without success.

Here is a reprex:

```
devtools::install_github('stefano-meschiari/latex2exp', ref = 'v0.9.0')
library(latex2exp)
plot(x = rnorm(10),
     y = rnorm(10),
     ylab = TeX(r"($\lceil a+b \rceil$)"))
```

![Screenshot 2022-01-21 at 16 46 39](https://user-images.githubusercontent.com/17910063/150556695-fbb5d37b-d2ff-4fb0-9011-0d5f4291798d.png)

Am I missing something?

**Comment by stefano-meschiari** [comment]
Interesting, the same reprex on my system appears to work correctly:

![image](https://user-images.githubusercontent.com/2151723/150598805-aaadf123-5c29-4707-a717-8ecd34d840f8.png)

(note that with default margins, the leftmost few pixels y-axis label gets cut off a bit -- that's an issue with base graphics, not latex2exp; increasing margins fixes it).

Could you double-check the version of `latex2exp` loaded is indeed 0.9.0, and paste the output of `sessionInfo()` here?

**Comment by AntoineSoetewey** [comment]
I updated everything and now it works fine.

Thanks again !
