### ISSUE TITLE
Square brakets apparently need to be escaped

### ISSUE THREAD

**Issue by alusiani** [stefano-meschiari/latex2exp#48]
Hi,

thanks for this very useful package!

I notice that apparently square brakets need to be escaped to prevent being ignored, together with whatever is enclosed.
```R
plot(TeX(r"($a [b]$)"))
```
just shows "a", while
```R
plot(TeX(r"($a \[b\]$)"))
```
shows "a[b]"

It would be nicer that square brakets be treated as in LaTeX without a dedicated escaping.

Greetings!

Alberto

**Comment by alarsyo** [comment]
Additionally, using square brackets seems to break subscript and superscript syntax:

```r
plot(TeX(r"(a $\[b\]_{c}$)"))
```

shows "a[b]"

```r
plot(TeX(r"(a $\[b\]^{c}$)"))
```

shows "a[b]" as well
