### ISSUE TITLE
Render issues of parentheses \left[, ...

### ISSUE THREAD

**Issue by Pentaonia** [stefano-meschiari/latex2exp#50]
Hi, 
when I use for example 

`plot(TeX("Day time $\ \\left[ hours \\right] $"), cex=2, main="")`

R does not display the brackets. 
It looks like this:
![image](https://user-images.githubusercontent.com/93387223/171921591-34c814ce-e46a-43d7-9b3c-d8a0afc29eb6.png)

When I use this instead:
`plot(TeX("Day time $\ \\lbrack hours \\rbrack $"), cex=2, main="")`

it renders properly. 

![image](https://user-images.githubusercontent.com/93387223/171921986-23279a2d-0269-4748-8fd5-4d07dae0bb68.png)

**Comment by stefano-meschiari** [comment]
@Pentaonia sorry for the delay in triaging this. What version of R are you using and on which system?

On my system, your example renders correctly:
![image](https://user-images.githubusercontent.com/2151723/189502006-abdc9d5c-b61f-442d-811e-6b124bc972b7.png)

**Comment by stefano-meschiari** [comment]
Closing since I was not able to reproduce. Feel free to reopen if you can share a way to reproduce this bug.
