### ISSUE TITLE
latex2exp under windows does not accept \\

### ISSUE THREAD

**Issue by Christoph999** [stefano-meschiari/latex2exp#6]
I am using windows and the \ are not accepted, eg \alpha in the legend is displayed as \alpha. Any feedback would be highly appreciated.

**Comment by JBLecomte** [comment]
Works fine for me on Windows, you have to use a double \\ to make it work. Like in the Readme file TeX('$\\alpha^\\beta$')

**Comment by stefano-meschiari** [comment]
^What Jean-Baptiste said. You need to escape the backslash.

**Comment by Christoph999** [comment]
Sorry, stupid mistake on my part. Thank you for your support!
