### ISSUE TITLE
Italics in math mode and minus sign

### ISSUE THREAD

**Issue by spencerwoody** [stefano-meschiari/latex2exp#9]
To match TeX better, Latin characters should be in italics by default in mathmode, and $-$ should give a minus sign instead of a hyphen.

Otherwise, this package is perfect.

**Comment by stefano-meschiari** [comment]
Sorry for the delay in answering this issue!

$-$ is now represented correctly with a minus sign character.
It's not possible to italicize symbols such as $\alpha$ because of plotmath limitations (only letters to be able to be italicized).
